name: Richard Deployment

on:
  push:
    branches: [production]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /home/mid-9-tech/mid9tech-landing-page
            git fetch origin
            git checkout production
            git pull
            npm install
            npm run build
            pm2 reload all
